---
- name: Create minimal CentOS
  hosts: all

  tasks:
#  - name: Include vars
#    include_vars: "{{ item }}.yml"
#    loop:
#      - list
#      - list

  - name: Install minimal GUI and reboot
    import_tasks: tasks/install_minimal_gui.yml

  - name: Install essentials for build
    import_tasks: tasks/build_essential.yml

  - name: Install minimal browser
    import_tasks: tasks/install_minimal_browser.yml

  - name: Install minimal pdf viewer
    import_tasks: tasks/install_minimal_pdf_viewer.yml

  - name: Remove essentials for build
    import_tasks: tasks/remove_build_essential.yml

  - name: Remove files and dirs
    import_tasks: tasks/remove.yml

  - name: Rebuild RPM DBs
    import_tasks: tasks/rebuild_rpm_dbs.yml

  - name: Reduce kernel
    import_tasks: tasks/reduce_core.yml