---
- name: Remove cached files
  file:
    state: "{{ item }}"
    path: /var/cache/
    owner: root
    group: root
    mode: 0777
  with_items:
    - absent
    - directory

- name: Remove logs
  file:
    state: "{{ item }}"
    path: /var/log
    owner: root
    group: root
    mode: 0777
  with_items:
    - absent
    - directory

- name: Remove doc, manpages and info
  file:
    state: absent
    path: "/usr/share/{{ item }}"
  loop:
    - doc
    - man
    - info

- name: Register unused locales in /usr/lib/locale
  find:
    paths: /usr/lib/locale
    pattern: ^(?!en_US.utf8)
  register: lib_locale_remove

- name: Remove unused locales in /usr/lib/locale
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ lib_locale_remove }}"

  - name: Register unused locales in /usr/share/locale
  find:
    paths: /usr/share/locale
    pattern: ^(?!en_US)
  register: lib_share_remove

- name: Remove unused locales in /usr/share/locale
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ lib_share_remove }}"

- name: Remove leaf packages with yum
  yum:
    autoremove: yes

- name: Clear yum cache
  command: yum clean all